services:
  base:
    build: .

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8002:8000"
    environment:
      - SERVICE_PORT=8000
      - SERVICE_NAME=products
  
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8003:8000"
    environment:
      - SERVICE_PORT=8000
      - SERVICE_NAME=auth
  
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "1234"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

networks:
    app_network:
        external: true